name: Build
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: Build
    steps:
    - name: Release
      uses: nu12/templates/actions/build/docker@main
      with:
        tag: 'latest'
        registry-password: '${{ secrets.TOKEN }}'
        push: ${{ github.event_name == 'push' }}